module.exports.adminAuth = require('./admin/auth.validation')
module.exports.AuthValidationClient = require('./client/auth.validation')
module.exports.LoginValidation = require('./login/login.validation')
module.exports.FactureValidation = require('./admin/facture.validation')
module.exports.ClientFactureValidation = require('./client/facture.validation')
module.exports.gestionCompteValidation = require('./admin/gestionCompte.validation')