module.exports.authAdmin = require('./admin/auth.controller')
module.exports.authControllerUser = require('./client/auth.controller')
module.exports.loginController = require('./login.controller')
module.exports.FactureController = require('./admin/facture.controller')
module.exports.ClientFactureController = require('./client/facture.controller')
module.exports.gestionCompteController = require('./admin/gestionCompte.controller')