module.exports.Admin = require('./administrateur.model')
module.exports.Client = require('./client.model')
module.exports.Material = require('./material.model')
module.exports.Facture = require('./facture.model')
module.exports.Type = require('./type.model')
module.exports.StaticInf = require('./staticInformation.model')